---

run:
  timeout: 30m

  concurrency: 2

  issue-exit-code: 1

  tests: true

  allow-parallel-runners: true

output:
  path-prefix: "backend"

linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - errcheck
    - exportloopref
    - goconst
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - lll - TODO: enable later
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  gosec:
    excludes:
      - G109 # Integer overflow
      - G204 # Subprocess arguments
      - G203 # Escape HTML
      - G402 # Insecure skip verify
      - G505 # Allow sha1
      - G401 # Allow sha1
    config:
      G306: "0660"

  misspell:
    ignore-words:
      - payed # Requires alter table...